### ISSUE TITLE
[Question] Setting up DVWA on docker-xampp

### ISSUE THREAD

**Issue by joe733** [tomsik68/docker-xampp#46]
Hello,

I'm running Docker on **Linux**. I use the following command to start the container:

```bash
docker run --name DockerXAMPP -p 41061:22 -p 41062:80 -d tomsik68/xampp
```

I copied [DVWA](https://github.com/digininja/DVWA) files to `DockerXAMPP:/opt/lampp/htdocs/DVWA/`. After navigating to `http://localhost:41062/DVWA/setup.php`, when I click on <kbd>Create / Reset Database</kbd>, it errors into:

```
Fatal error: Uncaught mysqli_sql_exception: Access denied for user 'dvwa'@'localhost' (using password: YES) in 
/opt/lampp/htdocs/DVWA/dvwa/includes/DBMS/MySQL.php:13
Stack trace: 
#0 /opt/lampp/htdocs/DVWA/dvwa/includes/DBMS/MySQL.php(13): mysqli_connect('127.0.0.1', 'dvwa', 'p@ssw0rd', '', '3306')
#1 /opt/lampp/htdocs/DVWA/setup.php(23): include_once('/opt/lampp/htdo...')
#2 {main} thrown in /opt/lampp/htdocs/DVWA/dvwa/includes/DBMS/MySQL.php on line 13
```

Are the database defaults different? Where am I going wrong?

All help is appreciated!
Thank you!

**Comment by joe733** [comment]
Had to update `config.inc.php` with these values:

```php
$_DVWA[ 'db_user' ]     = 'root';
$_DVWA[ 'db_password' ] = '';
```
